<?php
global $READER, $msql;
$plugins = !strpos($_SERVER['REQUEST_URI'], 'savePlugin') ? array_values(array_diff(scandir("libs/plugins"), ['.', '..'])) : '';
define("DS", "\\", false);
define("DS_FORWARD", "/", false);
define("ROOT", dirname(__FILE__).DS, false);
define("ROOT_FORWARD", dirname(__FILE__).DS_FORWARD, false);
define("ROOT_DB", dirname(__FILE__).DS."db".DS, false);
define("ROOT_DB_FORWARD", dirname(__FILE__).DS_FORWARD."db".DS_FORWARD, false);
define("ROOT_HISTORY", dirname(__FILE__).DS."libs".DS."history".DS, false);
define("ROOT_HISTORY_FORWARD", dirname(__FILE__).DS_FORWARD."libs".DS_FORWARD."history".DS_FORWARD, false);
define("ROOT_DATA", dirname(__FILE__).DS."libs".DS."data".DS, false);
define("ROOT_DATA_FORWARD", dirname(__FILE__).DS_FORWARD."libs".DS_FORWARD."data".DS_FORWARD, false);
define("ROOT_DOC_FORWARD", $_SERVER['DOCUMENT_ROOT'].DS_FORWARD, false);
define("ROOT_DOC", str_replace("/","\\", $_SERVER['DOCUMENT_ROOT']).DS, false);
define("PPDB_CONNECT", $_SERVER['SERVER_NAME'] . ":" . $_SERVER['SERVER_PORT'], false);
define("PPDB_SERVER_NAME", $_SERVER['SERVER_NAME'], false);
define("PPDB_SERVER_PORT", $_SERVER['SERVER_PORT'], false);
define("SESSION_USER", isset($_SESSION['username']) ? $_SESSION['username'] : '', false);
define("JUSTIFY", "justify", false);
define("LEFT", "left", false);
define("CENTER", "center", false);
define("RIGHT", "right", false);
define("CAPITALIZE", "capitalize", false);
define("UPPERCASE", "uppercase", false);
define("LOWERCASE", "lowercase", false);
define("FILE_INFO", ["created", "updated", "size", "type"], false);
define("VIEW_ALL", -1, false);
define("BGCOLOR", "bgcolor");
define("PREVIEW_IMG","previewImg");
define("PREVIEW_VID","previewVid");
define("INCLUDE_WHITESPACE", true, false);
define("ROOT_UPLOAD", dirname(__FILE__).DS."libs".DS."uploads".DS, false);
define("ROOT_UPLOAD_FORWARD", dirname(__FILE__).DS_FORWARD."libs".DS_FORWARD."uploads".DS_FORWARD, false);
define("ROOT_PLUGIN", dirname(__FILE__).DS."libs".DS."plugins".DS, false);
define("ROOT_PLUGIN_FORWARD", dirname(__FILE__).DS_FORWARD."libs".DS_FORWARD."plugins".DS_FORWARD, false);
define("ROOT_THEME", dirname(__FILE__).DS."libs".DS."themes".DS, false);
define("ROOT_THEME_FORWARD", dirname(__FILE__).DS_FORWARD."libs".DS_FORWARD."themes".DS_FORWARD, false);

?>
